name: cjtoph
description: "none"
publish_to: 'none'

version: 2.1.3+14

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  url_launcher: ^6.3.0
  http: ^1.4.0
  shared_preferences: ^2.2.3   # toptop_history
  connectivity_plus: ^6.1.4
  new_version_plus: ^0.1.1   # 2.1.0
  version: ^3.0.2   # 2.1.0
  in_app_update: 4.2.3   # 2.1.0 캐럿 뺌
  store_redirect: ^2.0.1   # 2.1.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/cjtoph_icon.png"
  remove_alpha_ios: true

  windows:
    generate: true
    image_path: "assets/icon/cjtoph_icon.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/icon/cjtoph_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/