name: cjtoph
description: "none"
publish_to: 'none'

version: 2.0.2+3

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.7.0
  url_launcher: ^6.2.5
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/cjtoph_icon.png"
  remove_alpha_ios: true

  windows:
    generate: true
    image_path: "assets/icon/cjtoph_icon.png"
    icon_size: 256

  macos:
    generate: true
    image_path: "assets/icon/cjtoph_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/